### ISSUE TITLE
`joinRaw` methods produce equality check error when preventDuplicateJoins flag is up

### ISSUE THREAD

**Issue by jclausen** [coldbox-modules/quick#137]
The following query:

```
getInstance( "MyEntity" )
       .newQuery()
      .select( "id,other.id" )
      .leftJoinRaw( "myOtherTable as other", "FK_otherTable", "other.id" )
      .get()
```

Will throw the following error because there is no `toSQL` method on `qb.models.Query.JoinClause`:

```
coldfusion.runtime.CfJspPage$MemberFunctionInvocationException: An exception occurred while calling the function find.
    at coldfusion.runtime.CfJspPage.invokeMethodHandle(CfJspPage.java:3817)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3667)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3561)
    at cfQueryBuilder2ecfc202079901$funcJOIN.runFunction(/app/lib/modules/cfmigrations/modules/qb/models/Query/QueryBuilder.cfc:614)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4073)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4054)
    at cfQueryBuilder2ecfc202079901$funcJOINRAW.runFunction(/app/lib/modules/cfmigrations/modules/qb/models/Query/QueryBuilder.cfc:724)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4073)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4054)
    at cfQueryBuilder2ecfc202079901$funcLEFTJOINRAW.runFunction(/app/lib/modules/cfmigrations/modules/qb/models/Query/QueryBuilder.cfc:750)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:835)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:641)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3506)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3481)
    at coldfusion.runtime.CFPage.invoke(CFPage.java:14464)
    at cfBaseEntity2ecfc1996348628$funcFORWARDTOQB.runFunction(/app/lib/modules/quick/models/BaseEntity.cfc:2975)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:287)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4132)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4112)
    at cfBaseEntity2ecfc1996348628$funcONMISSINGMETHOD.runFunction(/app/lib/modules/quick/models/BaseEntity.cfc:2720)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:597)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4073)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4054)
    at coldfusion.runtime.SuperScope.invoke(SuperScope.java:18)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3506)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3481)
    at cfCBORMCompatEntity2ecfc1889576928$funcONMISSINGMETHOD.runFunction(/app/lib/modules/quick/models/CBORMCompatEntity.cfc:181)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:553)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:484)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:447)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:398)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:371)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:349)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:851)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:613)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:438)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3584)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3561)
```

The current workaround is to set `preventDuplicateJoins` to false in the query

**Comment by elpete** [comment]
This has been fixed in qb [8.4.7](https://github.com/coldbox-modules/qb/releases/tag/v8.4.7).
