### ISSUE TITLE
Scope WithRecursive() Exception Error: "Element RELATIONNAME is undefined in ARGUMENTS"

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/quick#175]
Creating a scope in a Quick entity that uses the `withRecursive()` method will trigger an exception error: 
_"Element RELATIONNAME is undefined in ARGUMENTS"_

I believe Quick should call QB's `with()` method but instead it calls `with()` within QuickBuilder instead.

Here's some code to reproduce.  You can change it to anything as long as you're using `withRecursive()`
```
function scopeForceParents( query ) {

        // Important: Move the where statement to the CTE and reset the top level query where statement
        var wheres = duplicate( query.getWheres() );
        query.setWheres( [] );
        
        // CTE that grabs all the desired ids and recursively goes up and gets the parents.
        // note: there may be dupes in this hierarchy - we filter them out later.
        query.withRecursive( "hierarchy", function( q ) {

            q.select( [ "category.id", "category.parentId" ] )
                .selectRaw( "0 as level" )
                .from( "category" )
                .setWheres( wheres );

            q.unionAll( function( q ) {

                q.select( [ "category.id", "category.parentId" ] )
                .selectRaw( "(level + 1) as level" )
                .from( "category" )
                // go up the tree
                .join( "hierarchy", "category.id", "=", "hierarchy.parentId" );

            } );

        }, [ "id", "parentId", "level" ] )
        // finally join with a subquery that references a distinct version of ids from the hierarchy
        .joinSub( "hierarchy", function( q ) {
            
            q.select( "id" )
                .distinct()
                .from( "hierarchy" );

        }, "category.id", "=", "hierarchy.id" );

    }
```    

Stack Trace Excerpt:
```
coldfusion.runtime.UndefinedElementException: Element RELATIONNAME is undefined in ARGUMENTS.
    at coldfusion.runtime.DotResolver.resolveSplitNameInMap(DotResolver.java:185)
    at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:2405)
    at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:2728)
    at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:2718)
    at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:2698)
    at cfBaseEntity2ecfc545092397$funcWITH.runFunction(D:\Dropbox\Repositories\my-project\modules\quick\models\BaseEntity.cfc:2397)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:554)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:485)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:448)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:399)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:372)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:609)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:835)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:641)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3549)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3524)
    at cfQuickBuilder2ecfc1083613895$funcWITH.runFunction(D:\Dropbox\Repositories\my-project\modules\quick\models\QuickBuilder.cfc:548)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:554)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:485)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:448)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:399)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:372)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:609)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4116)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4097)
    at cfQueryBuilder2ecfc1660656796$funcWITHRECURSIVE.runFunction(D:\Dropbox\Repositories\my-project\modules\qb\models\Query\QueryBuilder.cfc:2247)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:554)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:485)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:448)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:399)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:372)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:288)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:830)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:613)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:438)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3627)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:3604)
    at cfCategoryQ2ecfc71142227$funcSCOPEFORCEPARENTS.runFunction(D:\Dropbox\Repositories\my-project\modules_app\mymodule\models\category\CategoryQ.cfc:53)
```

**Comment by homestar9** [comment]
I believe this bug was fixed in a later version of Quick.  I also tweaked the query so it works with MSSQL:

```
function scopeForceParents( query ) {

        // Important: Move the where statement to the CTE and reset the top level query where statement
        var wheres = duplicate( query.getWheres() );
        query.setWheres( [] );
        
        // CTE that grabs all the desired ids and recursively goes up and gets the parents.
        // note: there may be dupes in this hierarchy - we filter them out later.
        query.withRecursive( "hierarchy", function( q ) {

            q.select( [ "category.id", "category.parentId" ] )
                .selectRaw( "0 as level" )
                .from( "category" )
                .setWheres( wheres );

            q.unionAll( function( q ) {

                q.select( [ "category.id", "category.parentId" ] )
                .selectRaw( "(level + 1) as level" )
                .from( "category" )
                // go up the tree
                .join( "hierarchy", "category.id", "=", "hierarchy.parentId" );

            } );

        }, [] )
        // finally join with a subquery that references a distinct version of ids from the hierarchy
        .joinSub( "hierarchy", function( q ) {
            
            q.selectRaw( "DISTINCT [id]" )
                .from( "hierarchy" );

        }, "category.id", "=", "hierarchy.id" );

    }
```
